[project]
name = "lerobot-S0101-gym"
version = "0.1.0"
description = "Basic S0101 gym environment"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.2",
    "ipython>=9.7.0",
    "lerobot[envs]",
    "mujoco>=3.3.7",
    "torch>=2.2.1",
]
